#!/usr/bin/env python3
"""Push tools/books.json out into the static files.

    python3 tools/sync.py            # rewrite in place
    python3 tools/sync.py --check    # report what would change, touch nothing

Generated, in this order:

  * the link-preview block (canonical + Open Graph + Twitter) in the <head>
    of every summary page and of index.html, between marker comments
  * the book-nav.css / book-nav.js includes on every summary page
  * the book list embedded in book-nav.js, which drives related + prev/next
  * the shelf list in index.html, between marker comments

The site still has no build step: everything this writes is committed plain
static HTML. Re-run it after editing tools/books.json, then run
tools/make-og-images.py if a title, blurb or palette changed.
"""

import argparse
import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "tools" / "books.json").read_text(encoding="utf-8"))
SITE = DATA["site"]
BOOKS = DATA["books"]
SHELVES = DATA["shelves"]

HEAD_START = "<!-- link-preview:start — generated by tools/sync.py -->"
HEAD_END = "<!-- link-preview:end -->"
LIST_START = "      <!-- book-list:start — generated by tools/sync.py -->"
LIST_END = "      <!-- book-list:end -->"
README_START = "<!-- contents:start — generated by tools/sync.py -->"
README_END = "<!-- contents:end -->"
NAV_START = "  /* BOOK-NAV-DATA:START */"
NAV_END = "  /* BOOK-NAV-DATA:END */"


def esc(value):
    return html.escape(value, quote=True)


def replace_block(text, start, end, body):
    """Swap the marked block, or return None if the markers are absent."""
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    if not pattern.search(text):
        return None
    return pattern.sub(lambda _: start + body + end, text, count=1)


def preview_block(*, title, description, url, image, kind):
    lines = [
        "",
        f'<link rel="canonical" href="{url}">',
        f'<meta property="og:type" content="{kind}">',
        f'<meta property="og:site_name" content="{esc(SITE["name"])}">',
        f'<meta property="og:title" content="{esc(title)}">',
        f'<meta property="og:description" content="{esc(description)}">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:image" content="{image}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{esc(title)}">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{esc(title)}">',
        f'<meta name="twitter:description" content="{esc(description)}">',
        f'<meta name="twitter:image" content="{image}">',
        "",
    ]
    return "\n".join(lines)


def ensure_head(text, block, extra_head_links=()):
    """Insert or refresh the preview block (plus any <link>s) before </head>."""
    swapped = replace_block(text, HEAD_START, HEAD_END, block)
    if swapped is None:
        if "</head>" not in text:
            raise SystemExit("no </head> found")
        swapped = text.replace("</head>", HEAD_START + block + HEAD_END + "\n</head>", 1)
    for link in extra_head_links:
        if link not in swapped:
            swapped = swapped.replace("</head>", link + "\n</head>", 1)
    return swapped


def ensure_script(text, tag):
    if tag in text:
        return text
    if "</body>" not in text:
        raise SystemExit("no </body> found")
    return text.replace("</body>", tag + "\n</body>", 1)


def page_description(text, fallback):
    found = re.search(r'<meta name="description" content="(.*?)"', text, re.S)
    return html.unescape(found.group(1)) if found else fallback


def nav_data():
    payload = {
        "books": [
            {
                "slug": b["slug"],
                "title": b["title"],
                "author": b["author"],
                "related": b.get("related", []),
            }
            for b in BOOKS
        ]
    }
    return "\n  var DATA = " + json.dumps(payload, ensure_ascii=False, indent=2).replace(
        "\n", "\n  "
    ) + ";\n"


def index_rows():
    out = ["\n"]
    for shelf in SHELVES:
        shelf_books = [b for b in BOOKS if b["shelf"] == shelf["id"]]
        if not shelf_books:
            continue
        out.append(f'''      <section class="shelf" data-shelf="{shelf["id"]}" aria-labelledby="shelf-{shelf["id"]}">
        <div class="shelf__head">
          <h2 id="shelf-{shelf["id"]}">{esc(shelf["name"])}</h2>
          <span class="shelf__count">{len(shelf_books)}</span>
        </div>
        <div class="list">
''')
        for book in shelf_books:
            haystack = esc(f'{book["title"]} {book["author"]} {book["tag"]} {shelf["name"]}'.lower())
            out.append(f'''          <a class="row" href="{book["slug"]}.html" data-added="{book["added"]}" data-search="{haystack}">
            <span class="row__title">{esc(book["title"])}</span>
            <span class="row__author">{esc(book["author"])}</span>
            <span class="row__meta"><span class="tag">{esc(book["tag"])}</span><time class="row__added" datetime="{book["added"]}"></time><span class="row__arrow">→</span></span>
          </a>
''')
        out.append("        </div>\n      </section>\n\n")
    return "".join(out).rstrip("\n") + "\n"


def readme_table():
    shelf_names = {s["id"]: s["name"] for s in SHELVES}
    rows = [
        "",
        "| Summary | Author | Shelf | Print PDF | Added |",
        "| --- | --- | --- | --- | --- |",
    ]
    for book in BOOKS:
        pdf = f'[PDF]({book["pdf"].replace(" ", "%20")})' if book.get("pdf") else "—"
        rows.append(
            f'| [{book["title"]}]({book["slug"]}.html) | {book["author"]} '
            f'| {shelf_names[book["shelf"]]} | {pdf} | {book["added"]} |'
        )
    rows.append("")
    return "\n".join(rows)


def run(check):
    changed = []

    def write(path, before, after):
        if before == after:
            return
        changed.append(path.name)
        if not check:
            path.write_text(after, encoding="utf-8")

    # 1. book-nav.js data block
    nav_path = ROOT / "book-nav.js"
    nav_before = nav_path.read_text(encoding="utf-8")
    nav_after = replace_block(nav_before, NAV_START, NAV_END, nav_data())
    if nav_after is None:
        raise SystemExit("book-nav.js is missing its BOOK-NAV-DATA markers")
    write(nav_path, nav_before, nav_after)

    # 2. every summary page
    for book in BOOKS:
        path = ROOT / f"{book['slug']}.html"
        if not path.exists():
            raise SystemExit(f"missing page for {book['slug']}")
        before = path.read_text(encoding="utf-8")
        url = f"{SITE['base']}/{book['slug']}.html"
        block = preview_block(
            title=f"{book['title']} — {book['author']}",
            description=book["blurb"],
            url=url,
            image=f"{SITE['base']}/og/{book['slug']}.png",
            kind="article",
        )
        after = ensure_head(before, block, ['<link rel="stylesheet" href="book-nav.css">'])
        if '<meta name="description"' not in after:
            after = after.replace(
                HEAD_START,
                f'<meta name="description" content="{esc(book["blurb"])}">\n' + HEAD_START,
                1,
            )
        after = ensure_script(after, '<script src="book-nav.js" defer></script>')
        write(path, before, after)

    # 3. index
    index_path = ROOT / "index.html"
    before = index_path.read_text(encoding="utf-8")
    block = preview_block(
        title=f"{SITE['name']} — {SITE['byline']}",
        description=page_description(before, ""),
        url=f"{SITE['base']}/",
        image=f"{SITE['base']}/og/index.png",
        kind="website",
    )
    after = ensure_head(before, block)
    rows = replace_block(after, LIST_START, LIST_END, index_rows())
    if rows is None:
        raise SystemExit("index.html is missing its book-list markers")
    after = re.sub(r"<li>\d+ books</li>", f"<li>{len(BOOKS)} books</li>", rows, count=1)
    write(index_path, before, after)

    # 4. README contents table
    readme_path = ROOT / "README.md"
    before = readme_path.read_text(encoding="utf-8")
    after = replace_block(before, README_START, README_END, readme_table())
    if after is None:
        raise SystemExit("README.md is missing its contents markers")
    write(readme_path, before, after)

    if check:
        print("would rewrite: " + (", ".join(changed) if changed else "nothing"))
        return 1 if changed else 0
    print("rewrote: " + (", ".join(changed) if changed else "nothing"))
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    sys.exit(run(parser.parse_args().check))
